name: 🚀 Deploy Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Trigger Portainer DEV webhook
        run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK }}"
